# =============================================================================
# build-c4.ps1 — Phase 4: C4 Architecture (PowerShell)
# Output: $ArchOutputDir\04-architecture.md + $ArchDiagramsDir\*.mmd
# =============================================================================

param([switch]$Auto, [string]$Answers = "")

$ScriptDir = $PSScriptRoot
. (Join-Path $ScriptDir "_common.ps1")

# Step 3: accept -Auto / -Answers
if ($Auto) { $env:ARCH_AUTO = '1' }
if ($Answers) { $env:ARCH_ANSWERS = $Answers }


$OutputFile    = Join-Path $script:ArchOutputDir   "04-architecture.md"
$ContextMmd    = Join-Path $script:ArchDiagramsDir "context.mmd"
$ContainersMmd = Join-Path $script:ArchDiagramsDir "containers.mmd"
$DeploymentMmd = Join-Path $script:ArchDiagramsDir "deployment.mmd"
$DSLFile       = Join-Path $script:ArchDiagramsDir "workspace.dsl"
$Area          = "C4 Architecture"

$startTDebts = Get-Arch-TDebtCount
New-Item -ItemType Directory -Path $script:ArchDiagramsDir -Force | Out-Null

Write-Arch-Banner "📐  Step 4 of 6 — C4 Architecture"
Write-Arch-Dim "  We'll build a C4 architecture document: System Context (Level 1),"
Write-Arch-Dim "  Containers (Level 2), and Components (Level 3) using Mermaid diagrams."
Write-Host ""

# ── LEVEL 1 — System Context ─────────────────────────────────────────────────
Write-Host "── Level 1 — System Context ──" -ForegroundColor Cyan
Write-Arch-Dim "  One box for the system, plus the people and external systems that touch it."
Write-Host ""

$SystemName = Ask-Arch-Text "  System name (e.g. 'Order Platform'):"
if ([string]::IsNullOrWhiteSpace($SystemName)) { $SystemName = "System" }
$SystemDesc = Ask-Arch-Text "  One-line description of what the system does:"
if ([string]::IsNullOrWhiteSpace($SystemDesc)) { $SystemDesc = "TBD" }

$People = @()
Write-Host ""
Write-Arch-Dim "  People / personas that interact with the system."
Write-Host ""
while ($true) {
  $person = Ask-Arch-Text "  Person name (e.g. 'Customer', 'Admin') — Enter to stop:"
  if ([string]::IsNullOrWhiteSpace($person)) { break }
  $action = Ask-Arch-Text "    What does $person do with the system? (short phrase)"
  if ([string]::IsNullOrWhiteSpace($action)) { $action = "interacts with the system" }
  $People += [pscustomobject]@{ Name = $person; Action = $action }
  $more = Ask-Arch-YN "  Add another person?"
  if ($more -eq "no") { break }
}

$Externals = @()
Write-Host ""
Write-Arch-Dim "  External systems the system depends on (e.g. Stripe, Auth0, SAP)."
Write-Host ""
while ($true) {
  $ext = Ask-Arch-Text "  External system name — Enter to stop:"
  if ([string]::IsNullOrWhiteSpace($ext)) { break }
  $purpose = Ask-Arch-Text "    What do we use $ext for? (short phrase)"
  if ([string]::IsNullOrWhiteSpace($purpose)) { $purpose = "external integration" }
  $Externals += [pscustomobject]@{ Name = $ext; Purpose = $purpose }
  $more = Ask-Arch-YN "  Add another external system?"
  if ($more -eq "no") { break }
}

$ctxLines = @()
$ctxLines += "%% C4 Level 1 — System Context"
$ctxLines += "%% Auto-generated by c4-architecture skill"
$ctxLines += ""
$ctxLines += "flowchart TB"
$ctxLines += "  classDef person fill:#08427B,color:#fff,stroke:#052E56"
$ctxLines += "  classDef system fill:#1168BD,color:#fff,stroke:#0B4884"
$ctxLines += "  classDef external fill:#999,color:#fff,stroke:#666"
$ctxLines += ""
$ctxLines += "  system[`"<b>$SystemName</b><br/>[Software System]<br/>$SystemDesc`"]:::system"
for ($i = 0; $i -lt $People.Count; $i++) {
  $p = $People[$i]
  $ctxLines += "  person${i}[`"<b>$($p.Name)</b><br/>[Person]`"]:::person"
  $ctxLines += "  person${i} -->|$($p.Action)| system"
}
for ($i = 0; $i -lt $Externals.Count; $i++) {
  $x = $Externals[$i]
  $ctxLines += "  ext${i}[`"<b>$($x.Name)</b><br/>[External System]`"]:::external"
  $ctxLines += "  system -->|$($x.Purpose)| ext${i}"
}
$ctxLines -join "`n" | Set-Content -Path $ContextMmd -Encoding UTF8
Write-Host "  ✅ Saved: $ContextMmd" -ForegroundColor Green

# ── LEVEL 2 — Containers ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "── Level 2 — Containers ──" -ForegroundColor Cyan
Write-Arch-Dim "  Containers are deployable/runnable units: apps, services, databases,"
Write-Arch-Dim "  workers, brokers. Each should reference the ADR that justifies its tech."
Write-Host ""

$Containers = @()
while ($true) {
  $cname = Ask-Arch-Text "  Container name (e.g. 'Web App', 'Orders API', 'Orders DB') — Enter to stop:"
  if ([string]::IsNullOrWhiteSpace($cname)) { break }
  $cresp = Ask-Arch-Text "    Responsibility (one line):"
  if ([string]::IsNullOrWhiteSpace($cresp)) { $cresp = "TBD" }
  $ctech = Ask-Arch-Text "    Technology (e.g. 'Node.js 20 / Express', 'PostgreSQL 16'):"
  if ([string]::IsNullOrWhiteSpace($ctech)) { $ctech = "TBD" }
  $cadr = Ask-Arch-Text "    ADR reference (e.g. 'ADR-0002' — Enter for TBD):"
  if ([string]::IsNullOrWhiteSpace($cadr)) {
    $cadr = "TBD"
    Add-Arch-TDebt -Area $Area -Title "Container '$cname' has no ADR" `
      -Description "Container '$cname' is included without a decision record for its technology" `
      -Impact "Technology choice cannot be defended or revisited systematically"
  }
  $Containers += [pscustomobject]@{ Name = $cname; Resp = $cresp; Tech = $ctech; ADR = $cadr }
  $more = Ask-Arch-YN "  Add another container?"
  if ($more -eq "no") { break }
}

if ($Containers.Count -eq 0) {
  Add-Arch-TDebt -Area $Area -Title "No containers captured" `
    -Description "Container diagram has zero entries" `
    -Impact "Architecture cannot be implemented or reviewed without containers"
}

$Edges = @()
Write-Host ""
Write-Arch-Dim "  Now capture the main interactions between containers (optional)."
while ($true) {
  $ef = Ask-Arch-Text "  From container name — Enter to stop:"
  if ([string]::IsNullOrWhiteSpace($ef)) { break }
  $et = Ask-Arch-Text "    To container name:"
  if ([string]::IsNullOrWhiteSpace($et)) { continue }
  $el = Ask-Arch-Text "    Label (e.g. 'Reads from / Writes to', 'Publishes events'):"
  if ([string]::IsNullOrWhiteSpace($el)) { $el = "calls" }
  $Edges += [pscustomobject]@{ From = $ef; To = $et; Label = $el }
}

$contLines = @()
$contLines += "%% C4 Level 2 — Containers"
$contLines += "%% Auto-generated by c4-architecture skill"
$contLines += ""
$contLines += "flowchart TB"
$contLines += "  classDef container fill:#438DD5,color:#fff,stroke:#2E6295"
$contLines += ""
$contLines += "  subgraph sys[`"$SystemName`"]"
for ($i = 0; $i -lt $Containers.Count; $i++) {
  $c = $Containers[$i]
  $contLines += "    c${i}[`"<b>$($c.Name)</b><br/>[$($c.Tech)]<br/>$($c.Resp)`"]:::container"
}
$contLines += "  end"
$contLines += ""
foreach ($e in $Edges) {
  $fromIdx = -1; $toIdx = -1
  for ($i = 0; $i -lt $Containers.Count; $i++) {
    if ($Containers[$i].Name -eq $e.From) { $fromIdx = $i }
    if ($Containers[$i].Name -eq $e.To)   { $toIdx   = $i }
  }
  if ($fromIdx -ge 0 -and $toIdx -ge 0) {
    $contLines += "  c${fromIdx} -->|$($e.Label)| c${toIdx}"
  }
}
$contLines -join "`n" | Set-Content -Path $ContainersMmd -Encoding UTF8
Write-Host "  ✅ Saved: $ContainersMmd" -ForegroundColor Green

# ── LEVEL 3 — Components ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "── Level 3 — Components ──" -ForegroundColor Cyan
Write-Arch-Dim "  For each container with non-trivial internals, capture its components."
Write-Host ""

$ComponentFiles = @()
foreach ($c in $Containers) {
  $drill = Ask-Arch-YN "  Drill into [$($c.Name)] components?"
  if ($drill -eq "no") { continue }

  $cslug = Get-Arch-Slug -Text $c.Name
  $compFile = Join-Path $script:ArchDiagramsDir "components-$cslug.mmd"
  $ComponentFiles += [pscustomobject]@{ File = $compFile; Name = $c.Name }

  $comps = @()
  while ($true) {
    $compname = Ask-Arch-Text "    Component name (e.g. 'OrderController') — Enter to stop:"
    if ([string]::IsNullOrWhiteSpace($compname)) { break }
    $compresp = Ask-Arch-Text "      Responsibility (one line):"
    if ([string]::IsNullOrWhiteSpace($compresp)) { $compresp = "TBD" }
    $comps += [pscustomobject]@{ Name = $compname; Resp = $compresp }
    $more = Ask-Arch-YN "    Add another component to [$($c.Name)]?"
    if ($more -eq "no") { break }
  }

  $cLines = @()
  $cLines += "%% C4 Level 3 — Components of $($c.Name)"
  $cLines += "%% Auto-generated by c4-architecture skill"
  $cLines += ""
  $cLines += "flowchart TB"
  $cLines += "  classDef component fill:#85BBF0,color:#000,stroke:#5D82A8"
  $cLines += ""
  $cLines += "  subgraph cont[`"$($c.Name) (Container)`"]"
  for ($i = 0; $i -lt $comps.Count; $i++) {
    $co = $comps[$i]
    $cLines += "    co${i}[`"<b>$($co.Name)</b><br/>[Component]<br/>$($co.Resp)`"]:::component"
  }
  $cLines += "  end"
  $cLines -join "`n" | Set-Content -Path $compFile -Encoding UTF8
  Write-Host "    ✅ Saved: $compFile" -ForegroundColor Green
}

# ── Deployment view ──────────────────────────────────────────────────────────
Write-Host ""
Write-Host "── Deployment view (optional) ──" -ForegroundColor Cyan
$includeDepl = Ask-Arch-YN "  Include a deployment diagram?"
$deploymentIncluded = $false
if ($includeDepl -eq "yes") {
  $deploymentIncluded = $true
  $deplEnv = Ask-Arch-Text "  Deployment environment (e.g. 'AWS eu-west-1, VPC'):"
  if ([string]::IsNullOrWhiteSpace($deplEnv)) { $deplEnv = "TBD" }
  $deplNodes = Ask-Arch-Text "  Infrastructure nodes (comma-separated, e.g. 'ALB, ECS, RDS, S3'):"
  if ([string]::IsNullOrWhiteSpace($deplNodes)) { $deplNodes = "TBD" }

  $dLines = @()
  $dLines += "%% Deployment view — $deplEnv"
  $dLines += "%% Auto-generated by c4-architecture skill"
  $dLines += ""
  $dLines += "flowchart TB"
  $dLines += "  classDef node fill:#C8E1FA,color:#000,stroke:#5D82A8"
  $dLines += ""
  $dLines += "  subgraph env[`"$deplEnv`"]"
  $nodes = $deplNodes -split ','
  for ($i = 0; $i -lt $nodes.Count; $i++) {
    $n = $nodes[$i].Trim()
    if ([string]::IsNullOrWhiteSpace($n)) { continue }
    $dLines += "    n${i}[`"$n`"]:::node"
  }
  $dLines += "  end"
  $dLines -join "`n" | Set-Content -Path $DeploymentMmd -Encoding UTF8
  Write-Host "  ✅ Saved: $DeploymentMmd" -ForegroundColor Green
}

# ── Structurizr DSL export ───────────────────────────────────────────────────
$includeDsl = Ask-Arch-YN "  Also export a Structurizr DSL workspace? (optional)"
if ($includeDsl -eq "yes") {
  $dslLines = @()
  $dslLines += "workspace `"$SystemName`" `"$SystemDesc`" {"
  $dslLines += "  model {"
  $dslLines += "    sys = softwareSystem `"$SystemName`" `"$SystemDesc`" {"
  for ($i = 0; $i -lt $Containers.Count; $i++) {
    $c = $Containers[$i]
    $dslLines += "      c${i} = container `"$($c.Name)`" `"$($c.Resp)`" `"$($c.Tech)`""
  }
  $dslLines += "    }"
  for ($i = 0; $i -lt $People.Count; $i++) {
    $p = $People[$i]
    $dslLines += "    p${i} = person `"$($p.Name)`""
    $dslLines += "    p${i} -> sys `"$($p.Action)`""
  }
  for ($i = 0; $i -lt $Externals.Count; $i++) {
    $x = $Externals[$i]
    $dslLines += "    x${i} = softwareSystem `"$($x.Name)`" `"External`""
    $dslLines += "    sys -> x${i} `"$($x.Purpose)`""
  }
  $dslLines += "  }"
  $dslLines += "  views {"
  $dslLines += "    systemContext sys `"Context`" { include * autolayout }"
  $dslLines += "    container    sys `"Containers`" { include * autolayout }"
  $dslLines += "  }"
  $dslLines += "}"
  $dslLines -join "`n" | Set-Content -Path $DSLFile -Encoding UTF8
  Write-Host "  ✅ Saved: $DSLFile" -ForegroundColor Green
}

# ── Consolidated document ────────────────────────────────────────────────────
$DateNow = Get-Date -Format "yyyy-MM-dd"
$docLines = @()
$docLines += "# $SystemName — Architecture Overview"
$docLines += ""
$docLines += "**Version:** 1.0 — $DateNow"
$docLines += "**Status:** Draft"
$docLines += ""
$docLines += "## 1. Purpose & Scope"
$docLines += ""
$docLines += $SystemDesc
$docLines += ""
$docLines += "## 2. Level 1 — System Context"
$docLines += ""
$docLines += '```mermaid'
$docLines += (Get-Content -Path $ContextMmd -Raw)
$docLines += '```'
$docLines += ""
$docLines += "### People & external systems"
$docLines += ""
$docLines += "| Kind | Name | Purpose |"
$docLines += "|---|---|---|"
foreach ($p in $People)    { $docLines += "| Person | $($p.Name) | $($p.Action) |" }
foreach ($x in $Externals) { $docLines += "| External system | $($x.Name) | $($x.Purpose) |" }
$docLines += ""
$docLines += "## 3. Level 2 — Containers"
$docLines += ""
$docLines += '```mermaid'
$docLines += (Get-Content -Path $ContainersMmd -Raw)
$docLines += '```'
$docLines += ""
$docLines += "### Containers"
$docLines += ""
$docLines += "| Container | Responsibility | Technology | ADR |"
$docLines += "|---|---|---|---|"
foreach ($c in $Containers) { $docLines += "| $($c.Name) | $($c.Resp) | $($c.Tech) | $($c.ADR) |" }
$docLines += ""
$docLines += "## 4. Level 3 — Components"
$docLines += ""
if ($ComponentFiles.Count -eq 0) {
  $docLines += "_No component-level diagrams were generated. Consider drilling into complex containers._"
} else {
  foreach ($cf in $ComponentFiles) {
    $docLines += "### $($cf.Name)"
    $docLines += ""
    $docLines += '```mermaid'
    $docLines += (Get-Content -Path $cf.File -Raw)
    $docLines += '```'
    $docLines += ""
  }
}
if ($deploymentIncluded) {
  $docLines += "## 5. Deployment View"
  $docLines += ""
  $docLines += '```mermaid'
  $docLines += (Get-Content -Path $DeploymentMmd -Raw)
  $docLines += '```'
  $docLines += ""
}
$docLines += "## 6. Cross-Cutting Concerns"
$docLines += ""
$docLines += "_Populate with references to the relevant ADRs: authentication, observability,"
$docLines += "error-handling strategy, secrets management, feature flags, etc._"
$docLines += ""
$docLines += "## 7. ADR Index"
$docLines += ""
$docLines += "See ``03-adr-index.md`` for the full list."
$docLines += ""
$docLines += "## 8. Risks & Technical Debts"
$docLines += ""
$docLines += "See ``05-technical-debts.md`` for the current register."
$docLines += ""

$docLines -join "`n" | Set-Content -Path $OutputFile -Encoding UTF8

$endTDebts = Get-Arch-TDebtCount
$newTDebts = $endTDebts - $startTDebts

Write-Arch-SuccessRule "✅ C4 Architecture Document Built"
Write-Host "  Main document: $OutputFile" -ForegroundColor Green
Write-Host "  Diagrams dir:  $script:ArchDiagramsDir" -ForegroundColor Green
if ($newTDebts -gt 0) {
  Write-Host "  ⚠  $newTDebts technical debt(s) logged" -ForegroundColor Yellow
}
Write-Host ""
