#!/bin/bash
# =============================================================================
# build-c4.sh — Phase 4: C4 Architecture
# Produces the architecture document using the C4 model (Context / Container /
# Component). Writes Mermaid .mmd files and a consolidated 04-architecture.md.
# =============================================================================

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_common.sh
source "$SCRIPT_DIR/_common.sh"

# Step 3: accept --auto / --answers flags
arch_parse_flags "$@"


OUTPUT_FILE="$ARCH_OUTPUT_DIR/04-architecture.md"
CONTEXT_MMD="$ARCH_DIAGRAMS_DIR/context.mmd"
CONTAINERS_MMD="$ARCH_DIAGRAMS_DIR/containers.mmd"
DEPLOYMENT_MMD="$ARCH_DIAGRAMS_DIR/deployment.mmd"
DSL_FILE="$ARCH_DIAGRAMS_DIR/workspace.dsl"
AREA="C4 Architecture"

start_tdebts=$(arch_current_tdebt_count)

mkdir -p "$ARCH_DIAGRAMS_DIR"

arch_banner "📐  Step 4 of 6 — C4 Architecture"
arch_dim "  We'll build a C4 architecture document: System Context (Level 1),"
arch_dim "  Containers (Level 2), and Components (Level 3) using Mermaid diagrams."
echo ""

# ── LEVEL 1 — System Context ─────────────────────────────────────────────────
printf '%b%b── Level 1 — System Context ──%b\n' "$ARCH_CYAN" "$ARCH_BOLD" "$ARCH_NC"
arch_dim "  One box for the system, plus the people and external systems that touch it."
echo ""

SYSTEM_NAME=$(arch_ask "  System name (e.g. 'Order Platform'):")
[ -z "$SYSTEM_NAME" ] && SYSTEM_NAME="System"
SYSTEM_DESC=$(arch_ask "  One-line description of what the system does:")
[ -z "$SYSTEM_DESC" ] && SYSTEM_DESC="TBD"

# Capture people/personas
declare_people=()
echo ""
arch_dim "  People / personas that interact with the system."
echo ""
while true; do
  person=$(arch_ask "  Person name (e.g. 'Customer', 'Admin') — Enter to stop:")
  if [ -z "$person" ]; then break; fi
  action=$(arch_ask "    What does $person do with the system? (short phrase)")
  [ -z "$action" ] && action="interacts with the system"
  declare_people+=("$person|$action")
  more=$(arch_ask_yn "  Add another person?")
  [ "$more" = "no" ] && break
done

# Capture external systems
declare_externals=()
echo ""
arch_dim "  External systems the system depends on (e.g. Stripe, Auth0, SAP)."
echo ""
while true; do
  ext=$(arch_ask "  External system name — Enter to stop:")
  if [ -z "$ext" ]; then break; fi
  purpose=$(arch_ask "    What do we use $ext for? (short phrase)")
  [ -z "$purpose" ] && purpose="external integration"
  declare_externals+=("$ext|$purpose")
  more=$(arch_ask_yn "  Add another external system?")
  [ "$more" = "no" ] && break
done

# Write Mermaid context diagram
system_slug=$(arch_slugify "$SYSTEM_NAME")
{
  echo "%% C4 Level 1 — System Context"
  echo "%% Auto-generated by c4-architecture skill"
  echo ""
  echo "flowchart TB"
  echo "  classDef person fill:#08427B,color:#fff,stroke:#052E56"
  echo "  classDef system fill:#1168BD,color:#fff,stroke:#0B4884"
  echo "  classDef external fill:#999,color:#fff,stroke:#666"
  echo ""
  echo "  system[\"<b>${SYSTEM_NAME}</b><br/>[Software System]<br/>${SYSTEM_DESC}\"]:::system"

  idx=0
  for entry in "${declare_people[@]:-}"; do
    [ -z "$entry" ] && continue
    name="${entry%%|*}"; act="${entry#*|}"
    pid="person${idx}"
    echo "  ${pid}[\"<b>${name}</b><br/>[Person]\"]:::person"
    echo "  ${pid} -->|${act}| system"
    idx=$((idx + 1))
  done

  idx=0
  for entry in "${declare_externals[@]:-}"; do
    [ -z "$entry" ] && continue
    name="${entry%%|*}"; purpose="${entry#*|}"
    xid="ext${idx}"
    echo "  ${xid}[\"<b>${name}</b><br/>[External System]\"]:::external"
    echo "  system -->|${purpose}| ${xid}"
    idx=$((idx + 1))
  done
} > "$CONTEXT_MMD"

printf '%b  ✅ Saved: %s%b\n' "$ARCH_GREEN" "$CONTEXT_MMD" "$ARCH_NC"

# ── LEVEL 2 — Containers ─────────────────────────────────────────────────────
echo ""
printf '%b%b── Level 2 — Containers ──%b\n' "$ARCH_CYAN" "$ARCH_BOLD" "$ARCH_NC"
arch_dim "  Containers are deployable/runnable units: apps, services, databases,"
arch_dim "  workers, brokers. Each should reference the ADR that justifies its tech."
echo ""

declare_containers=()
while true; do
  cname=$(arch_ask "  Container name (e.g. 'Web App', 'Orders API', 'Orders DB') — Enter to stop:")
  if [ -z "$cname" ]; then break; fi
  cresp=$(arch_ask "    Responsibility (one line):")
  [ -z "$cresp" ] && cresp="TBD"
  ctech=$(arch_ask "    Technology (e.g. 'Node.js 20 / Express', 'PostgreSQL 16'):")
  [ -z "$ctech" ] && ctech="TBD"
  cadr=$(arch_ask "    ADR reference (e.g. 'ADR-0002' — Enter for TBD):")
  if [ -z "$cadr" ]; then
    cadr="TBD"
    arch_add_tdebt "$AREA" "Container '$cname' has no ADR" \
      "Container '$cname' is included without a decision record for its technology" \
      "Technology choice cannot be defended or revisited systematically"
  fi
  declare_containers+=("$cname|$cresp|$ctech|$cadr")
  more=$(arch_ask_yn "  Add another container?")
  [ "$more" = "no" ] && break
done

if [ "${#declare_containers[@]:-0}" -eq 0 ]; then
  arch_add_tdebt "$AREA" "No containers captured" \
    "Container diagram has zero entries" \
    "Architecture cannot be implemented or reviewed without containers"
fi

# Capture container-to-container interactions
declare_edges=()
echo ""
arch_dim "  Now capture the main interactions between containers (optional)."
while true; do
  edge_from=$(arch_ask "  From container name — Enter to stop:")
  if [ -z "$edge_from" ]; then break; fi
  edge_to=$(arch_ask "    To container name:")
  if [ -z "$edge_to" ]; then continue; fi
  edge_label=$(arch_ask "    Label (e.g. 'Reads from / Writes to', 'Publishes events'):")
  [ -z "$edge_label" ] && edge_label="calls"
  declare_edges+=("$edge_from|$edge_to|$edge_label")
done

# Write Mermaid containers diagram
{
  echo "%% C4 Level 2 — Containers"
  echo "%% Auto-generated by c4-architecture skill"
  echo ""
  echo "flowchart TB"
  echo "  classDef container fill:#438DD5,color:#fff,stroke:#2E6295"
  echo "  classDef person fill:#08427B,color:#fff,stroke:#052E56"
  echo "  classDef external fill:#999,color:#fff,stroke:#666"
  echo ""
  echo "  subgraph sys[\"${SYSTEM_NAME}\"]"
  idx=0
  for entry in "${declare_containers[@]:-}"; do
    [ -z "$entry" ] && continue
    IFS='|' read -r cname cresp ctech cadr <<< "$entry"
    cid="c${idx}"
    echo "    ${cid}[\"<b>${cname}</b><br/>[${ctech}]<br/>${cresp}\"]:::container"
    idx=$((idx + 1))
  done
  echo "  end"
  echo ""

  # Edges (best-effort: match by order)
  for entry in "${declare_edges[@]:-}"; do
    [ -z "$entry" ] && continue
    IFS='|' read -r from_name to_name label <<< "$entry"
    # Find container indices by name
    from_idx=-1; to_idx=-1; ci=0
    for c in "${declare_containers[@]:-}"; do
      cn="${c%%|*}"
      if [ "$cn" = "$from_name" ]; then from_idx=$ci; fi
      if [ "$cn" = "$to_name" ];   then to_idx=$ci;   fi
      ci=$((ci + 1))
    done
    if [ "$from_idx" -ge 0 ] && [ "$to_idx" -ge 0 ]; then
      echo "  c${from_idx} -->|${label}| c${to_idx}"
    fi
  done
} > "$CONTAINERS_MMD"

printf '%b  ✅ Saved: %s%b\n' "$ARCH_GREEN" "$CONTAINERS_MMD" "$ARCH_NC"

# ── LEVEL 3 — Components (per container, loop) ───────────────────────────────
echo ""
printf '%b%b── Level 3 — Components ──%b\n' "$ARCH_CYAN" "$ARCH_BOLD" "$ARCH_NC"
arch_dim "  For each container with non-trivial internals, capture its components"
arch_dim "  (controllers, services, repositories, adapters)."
echo ""

declare_component_files=()
for entry in "${declare_containers[@]:-}"; do
  [ -z "$entry" ] && continue
  IFS='|' read -r cname _cresp _ctech _cadr <<< "$entry"

  drill=$(arch_ask_yn "  Drill into [$cname] components?")
  if [ "$drill" = "no" ]; then
    continue
  fi

  cslug=$(arch_slugify "$cname")
  comp_file="$ARCH_DIAGRAMS_DIR/components-${cslug}.mmd"
  declare_component_files+=("$comp_file|$cname")

  # Capture components
  comps=()
  while true; do
    compname=$(arch_ask "    Component name (e.g. 'OrderController') — Enter to stop:")
    if [ -z "$compname" ]; then break; fi
    compresp=$(arch_ask "      Responsibility (one line):")
    [ -z "$compresp" ] && compresp="TBD"
    comps+=("$compname|$compresp")
    more=$(arch_ask_yn "    Add another component to [$cname]?")
    [ "$more" = "no" ] && break
  done

  {
    echo "%% C4 Level 3 — Components of ${cname}"
    echo "%% Auto-generated by c4-architecture skill"
    echo ""
    echo "flowchart TB"
    echo "  classDef component fill:#85BBF0,color:#000,stroke:#5D82A8"
    echo ""
    echo "  subgraph cont[\"${cname} (Container)\"]"
    ci=0
    for ce in "${comps[@]:-}"; do
      [ -z "$ce" ] && continue
      IFS='|' read -r compn compr <<< "$ce"
      echo "    co${ci}[\"<b>${compn}</b><br/>[Component]<br/>${compr}\"]:::component"
      ci=$((ci + 1))
    done
    echo "  end"
  } > "$comp_file"

  printf '%b    ✅ Saved: %s%b\n' "$ARCH_GREEN" "$comp_file" "$ARCH_NC"
done

# ── Deployment view (optional) ───────────────────────────────────────────────
echo ""
printf '%b%b── Deployment view (optional) ──%b\n' "$ARCH_CYAN" "$ARCH_BOLD" "$ARCH_NC"
include_depl=$(arch_ask_yn "  Include a deployment diagram?")
deployment_included="no"
if [ "$include_depl" = "yes" ]; then
  deployment_included="yes"
  depl_env=$(arch_ask "  Deployment environment (e.g. 'AWS eu-west-1, VPC'):")
  [ -z "$depl_env" ] && depl_env="TBD"
  depl_nodes=$(arch_ask "  Infrastructure nodes (comma-separated, e.g. 'ALB, ECS, RDS, S3'):")
  [ -z "$depl_nodes" ] && depl_nodes="TBD"
  {
    echo "%% Deployment view — ${depl_env}"
    echo "%% Auto-generated by c4-architecture skill"
    echo ""
    echo "flowchart TB"
    echo "  classDef node fill:#C8E1FA,color:#000,stroke:#5D82A8"
    echo ""
    echo "  subgraph env[\"${depl_env}\"]"
    IFS=',' read -r -a nodes_arr <<< "$depl_nodes"
    ni=0
    for n in "${nodes_arr[@]:-}"; do
      n_trim="$(printf '%s' "$n" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      [ -z "$n_trim" ] && continue
      echo "    n${ni}[\"${n_trim}\"]:::node"
      ni=$((ni + 1))
    done
    echo "  end"
  } > "$DEPLOYMENT_MMD"
  printf '%b  ✅ Saved: %s%b\n' "$ARCH_GREEN" "$DEPLOYMENT_MMD" "$ARCH_NC"
fi

# ── Structurizr DSL export (optional) ────────────────────────────────────────
include_dsl=$(arch_ask_yn "  Also export a Structurizr DSL workspace? (optional)")
if [ "$include_dsl" = "yes" ]; then
  {
    echo "workspace \"${SYSTEM_NAME}\" \"${SYSTEM_DESC}\" {"
    echo "  model {"
    echo "    sys = softwareSystem \"${SYSTEM_NAME}\" \"${SYSTEM_DESC}\" {"
    idx=0
    for entry in "${declare_containers[@]:-}"; do
      [ -z "$entry" ] && continue
      IFS='|' read -r cname cresp ctech _cadr <<< "$entry"
      echo "      c${idx} = container \"${cname}\" \"${cresp}\" \"${ctech}\""
      idx=$((idx + 1))
    done
    echo "    }"

    idx=0
    for entry in "${declare_people[@]:-}"; do
      [ -z "$entry" ] && continue
      name="${entry%%|*}"; act="${entry#*|}"
      echo "    p${idx} = person \"${name}\""
      echo "    p${idx} -> sys \"${act}\""
      idx=$((idx + 1))
    done

    idx=0
    for entry in "${declare_externals[@]:-}"; do
      [ -z "$entry" ] && continue
      name="${entry%%|*}"; purpose="${entry#*|}"
      echo "    x${idx} = softwareSystem \"${name}\" \"External\""
      echo "    sys -> x${idx} \"${purpose}\""
      idx=$((idx + 1))
    done
    echo "  }"
    echo "  views {"
    echo "    systemContext sys \"Context\" { include * autolayout }"
    echo "    container    sys \"Containers\" { include * autolayout }"
    echo "  }"
    echo "}"
  } > "$DSL_FILE"
  printf '%b  ✅ Saved: %s%b\n' "$ARCH_GREEN" "$DSL_FILE" "$ARCH_NC"
fi

# ── Consolidated architecture document ───────────────────────────────────────
DATE_NOW=$(date '+%Y-%m-%d')
{
  echo "# ${SYSTEM_NAME} — Architecture Overview"
  echo ""
  echo "**Version:** 1.0 — ${DATE_NOW}"
  echo "**Status:** Draft"
  echo ""
  echo "## 1. Purpose & Scope"
  echo ""
  echo "${SYSTEM_DESC}"
  echo ""
  echo "## 2. Level 1 — System Context"
  echo ""
  echo "\`\`\`mermaid"
  cat "$CONTEXT_MMD"
  echo "\`\`\`"
  echo ""
  echo "### People & external systems"
  echo ""
  echo "| Kind | Name | Purpose |"
  echo "|---|---|---|"
  for entry in "${declare_people[@]:-}"; do
    [ -z "$entry" ] && continue
    name="${entry%%|*}"; act="${entry#*|}"
    echo "| Person | ${name} | ${act} |"
  done
  for entry in "${declare_externals[@]:-}"; do
    [ -z "$entry" ] && continue
    name="${entry%%|*}"; purpose="${entry#*|}"
    echo "| External system | ${name} | ${purpose} |"
  done
  echo ""
  echo "## 3. Level 2 — Containers"
  echo ""
  echo "\`\`\`mermaid"
  cat "$CONTAINERS_MMD"
  echo "\`\`\`"
  echo ""
  echo "### Containers"
  echo ""
  echo "| Container | Responsibility | Technology | ADR |"
  echo "|---|---|---|---|"
  for entry in "${declare_containers[@]:-}"; do
    [ -z "$entry" ] && continue
    IFS='|' read -r cname cresp ctech cadr <<< "$entry"
    echo "| ${cname} | ${cresp} | ${ctech} | ${cadr} |"
  done
  echo ""

  echo "## 4. Level 3 — Components"
  echo ""
  if [ "${#declare_component_files[@]:-0}" -eq 0 ]; then
    echo "_No component-level diagrams were generated. Consider drilling into complex containers._"
  else
    for entry in "${declare_component_files[@]:-}"; do
      [ -z "$entry" ] && continue
      IFS='|' read -r comp_file cname_src <<< "$entry"
      echo "### ${cname_src}"
      echo ""
      echo "\`\`\`mermaid"
      cat "$comp_file"
      echo "\`\`\`"
      echo ""
    done
  fi

  if [ "$deployment_included" = "yes" ]; then
    echo "## 5. Deployment View"
    echo ""
    echo "\`\`\`mermaid"
    cat "$DEPLOYMENT_MMD"
    echo "\`\`\`"
    echo ""
  fi

  echo "## 6. Cross-Cutting Concerns"
  echo ""
  echo "_Populate with references to the relevant ADRs: authentication, observability,"
  echo "error-handling strategy, secrets management, feature flags, etc._"
  echo ""

  echo "## 7. ADR Index"
  echo ""
  echo "See \`03-adr-index.md\` for the full list."
  echo ""

  echo "## 8. Risks & Technical Debts"
  echo ""
  echo "See \`05-technical-debts.md\` for the current register."
  echo ""
} > "$OUTPUT_FILE"

end_tdebts=$(arch_current_tdebt_count)
new_tdebts=$((end_tdebts - start_tdebts))

arch_success_rule "✅ C4 Architecture Document Built"
printf '%b  Main document: %s%b\n' "$ARCH_GREEN" "$OUTPUT_FILE" "$ARCH_NC"
printf '%b  Diagrams dir:  %s%b\n' "$ARCH_GREEN" "$ARCH_DIAGRAMS_DIR" "$ARCH_NC"
if [ "$new_tdebts" -gt 0 ]; then
  printf '%b  ⚠  %d technical debt(s) logged%b\n' "$ARCH_YELLOW" "$new_tdebts" "$ARCH_NC"
fi
echo ""
